{ ... }: {
  # Generated by /update.sh - do not update manually!
  # Last updated: 2026-08-14.
  napcat_version = "v4.18.19";
  napcat_url = "https://github.com/NapNeko/NapCatQQ/releases/download/v4.18.19/NapCat.Shell.zip";
  napcat_hash = "sha256-xbdCPR1bjFVdYs2eQFmxkIzAmG57XIWg9FD0qO0XCs8=";
  qq_version = "3.2.18-36580";
  qq_amd64_url = "https://dldir1v6.qq.com/qqfile/qq/QQNT/a5fab4ff/linuxqq_3.2.18-36580_amd64.deb";
  qq_amd64_hash = "sha256-xEw6tE+qX90XQS3e2MTudeUJNfx25hwgq1YFROHqfng=";
  qq_arm64_url = "https://dldir1v6.qq.com/qqfile/qq/QQNT/a5fab4ff/linuxqq_3.2.18-36580_arm64.deb";
  qq_arm64_hash = "sha256-7teJWRvvz5baJsaHmOwnkLgBcBxWOUCGpV2+MHH7Tic=";
}